ProjectTugas1/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
import profile_page.urls as profile_page
import status.urls as status
import friend.urls as friend
import stats.urls as stats
from django.views.generic.base import RedirectView

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^profile_page/', include(profile_page,namespace='profile_page')),
	url(r'^status/', include(status,namespace='status')),
    url(r'^friend/', include(friend,namespace='friend')),
    url(r'^', include('stats.urls', namespace='stats', app_name='stats')),
    url(r'^$', RedirectView.as_view(url = 'status/', permanent = True),name='index')
]

friend/urls.py
from django.conf.urls import url
from .views import index, add_friend
#from .views import add_activity

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend/', add_friend, name='add_friend'),
    
]

profile_page/urls.py
from django.conf.urls import url
from .views import index


urlpatterns = [
   url(r'^$', index, name='index'),
]

stats/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^stats/$', index, name='index'),
]

status/urls.py
from django.conf.urls import url
from .views import index,status


urlpatterns = [
   url(r'^$', index, name='index'),
   url(r'^status/$', index, name='index'),
   url(r'^add_todo/$', status, name='status'),
]

friend/models.py
from django.db import models
from django.utils import timezone
import pytz

# Create your models here.
class AddFriend(models.Model):
	def converTZ():
		return timezone.now() + timezone.timedelta(hours=0)

	name = models.CharField(max_length=27)
	url = models.URLField(max_length=27)
	created_date = models.DateTimeField(default=converTZ)
	

profile_page/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
    name = models.CharField(max_length=27)
    birthday = models.CharField(max_length =6)
    gender=models.CharField(max_length=6)
    description=models.CharField(max_length=21)
    expertise=models.ManyToManyField('Expertise')
    email = models.EmailField()

class Expertise(models.Model):
    expertise = models.CharField(max_length=27)

    # def __str__(self):
    #     return str(self.expertise)

stats/models.py
from django.db import models

# Create your models here.

status/models.py
from django.db import models

# Create your models here.


class Todo(models.Model):
	title = models.CharField(max_length=27)
	description = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

friend/forms.py
from django import forms

class Friend_Form(forms.Form):
	error_messages = {
		'required' : 'Isi input ini',
		'invalid' : 'Isi input ini dengan url'
	}

	name_attrs={
		'type': 'text',
        'class': 'todo-form-input-nameFriend',
        'placeholder':'Nama kamu...'
	}

	url_attrs={
		'type': 'url',
        'class': 'todo-form-input-urlFriend',
        'placeholder':'Url...'
	}
	
	name = forms.CharField(label='Name', required=True, max_length=100, empty_value='Anonymous', widget=forms.TextInput(attrs=name_attrs))
	url = forms.URLField(label='URL', required=True,max_length=100, empty_value='Anonymous', widget=forms.URLInput(attrs=url_attrs))

status/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong input status',
    }
    #title_attrs = {
    #   'type': 'text',
    #   'class': 'todo-form-input',
    #   'placeholder':'Masukan judul...'
    #}
    
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Update your status here '
    }

    #title = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import AddFriend
 
# Create your views here.
response = {}
def index(request):    
    todo = AddFriend.objects.all()
    response['todo'] = todo
    html = 'friend.html'
    response['friend_form'] = Friend_Form
    return render(request, html, response)

def add_friend(request):
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        todo = AddFriend(name=request.POST['name'],url=request.POST['url'])
        todo.save()
        return HttpResponseRedirect('/friend')

profile_page/views.py
from django.shortcuts import render
from .models import Profile, Expertise
# Create your views here.
response={}
def index(request):
    new_activity = Profile.objects.create(name='Savira',birthday = '29 oct',gender ='female',description='i love ice cream', email='maharanisavira29@gmail.com')
    new_activity.save()

    e1 = Expertise.objects.create(expertise='Fun Coding')
    e1.save()
    e2 = Expertise.objects.create(expertise='Modeling')
    e2.save()
    e3= Expertise.objects.create(expertise='Taking Test')
    e3.save()

    new_activity.expertise.add(e1)
    new_activity.expertise.add(e2)
    new_activity.expertise.add(e3)

    response['name'] =new_activity.name
    response['birthday'] =new_activity.birthday
    response['gender']=new_activity.gender
    response['description']=new_activity.description
    response['email']=new_activity.email
    response['expertise']=new_activity.expertise.all()
    html = 'profile_page/profile_page.html'
    return render(request, 'profile_page.html', response)

stats/views.py
from django.shortcuts import render
from profile_page.models import Profile
from friend.models import AddFriend
from status.models import Todo

profile = Profile.objects.last()
numb_of_feeds = Todo.objects.count()
numb_of_friends = AddFriend.objects.count()
latest_post = Todo.objects.last()
def index(request):
	response = {'name' : profile.name, 'feeds' : numb_of_feeds, 'friends' : numb_of_friends, 'latestPost' : latest_post}
	return render(request, 'stats.html', response)
# Create your views here.

status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Todo_Form
from .models import Todo

# Create your views here.
response = {}
def index(request):    
    response['author'] = "Thrisnadevany" #TODO Implement yourname
    todo = Todo.objects.all()
    response['todo'] = todo
    # html = 'status.html'
    response['todo_form'] = Todo_Form
    return render(request, 'update.html' , response)

def status(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        #response['title'] = request.POST['title']
        response['description'] = request.POST['description']
        todo = Todo(description=response['description'])
        todo.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

friend/templates/friend.html
{% extends "friend/layout/base.html" %}

{% block content %}
<section id="input"> 
    <h4 id="h3-add" style="margin-top: 75px">Add Friend</h4>
    <br>
        <form method="POST" action="{% url 'friend:add_friend' %}">
            {% csrf_token %}
            {{friend_form}} 
            <br>
            <button style="background-color: #0000FF;margin-left: 90%;width: 100px", type="submit" class="button btn-success">Add Friend</button>
        </form>
</section>
<section id="list-friend">
    <h4 class="friendList">List Friend</h4>
    <div class="friendList">
        {% if todo %}
            {% for data in todo %}
                <div class="col-lg-2">
                    {{data.name}}
                </div>
                <div class="col-lg-2">
                <a href="{{data.url}}">{{data.url}}</a>
                </div>   
                <div class="col-lg-2">
                    {{data.created_date}}
                </div>
            {% endfor %}
        {% else %}
        <div class="alert alert-danger text-center">
            <strong>Oops!</strong> Tidak ada data Todo.
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}

friend/templates/friend/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- bootstrap csss -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/friend.css' %}" /> 

    <title> 
        Tugas Kelompok 1
    </title>
</head>

<body style="background-color: #bbdefb">
    <header>
        {% include "profile_page/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <br>
    <footer>
      {% include "profile_page/partials/footer.html" %}
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

profile_page/templates/profile_page.html
{% extends "profile_page/layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
<!DOCTYPE html>

<html>
<head>
<style>
  .container{
    dispay:table;
    height: 150%;
    width: 100%;
  }
  div{
    display:table-cell;
    vertical-align: middle;
    padding-left:100px;
    width: 70%;
  }
  h1{
    font-size: 180%;
    text-align: left;
  }

  h3{
    text-align:left;
    font-size:150%;
    color: white;
    font-family:monospace;
  }

  </style>
  <title>Tugas Kelompok</title>
</head>

<h1 style="text-align: center; width:200px; margin-left:20px; color: white;">profile</h1>
<center>
  <body>
  <img class="img-circle" style="width:200px; height:200px" src= https://i.pinimg.com/236x/e0/5d/51/e05d51c857bba4ee264c305d20fd1c52.jpg>
  <h2 style="color:white;"> {{name}}</h2>
</hr>
<midle>
  <section class="container">
    <article>

    <div clas="row">
      <div class="col-sm-6">
        <h3>Birthday </h3>
        <h3>Gender </h3>
        <h3>Description </h3>
        <h3>Email </h3>
      </div>

      <div class="col-sm-6">
        <h3>{{birthday}}</h3>
        <h3>{{gender}}</h3>
        <h3>{{description}}</h3>
        <h3>{{email}}</h3>
      </div>

    </div>
  </article>
  </section>

</center>
</midle>

</body>
</html>
{% endblock %}

profile_page/templates/profile_page/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/profile_page.css' %}" /> 
</head>
<body style="background-color: #bbdefb">
	<header>
		{% include "profile_page/partials/header.html" %}
	</header>

	 <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>

	<footer>
		{% include "profile_page/partials/footer.html" %}
	</footer>
</body>

profile_page/templates/profile_page/partials/footer.html
 <p>&copy; 2017 Copyright Text</p>

profile_page/templates/profile_page/partials/header.html
<nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Ling In</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="/friend/">Friends</a></li>
      <li><a href="/status/">Status</a></li>
      <li><a href="/profile_page/">Profile</a></li>
      <li><a href="/stats/">Stats</a></li>
    </ul>
  </div>
</nav>

stats/templates/stats.html
{% extends "stats/layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
<head>
    <link href="https://fonts.googleapis.com/css?family=Patrick+Hand+SC|Bitter" rel="stylesheet">
</head>
<style>
	.img-circle {
     border-radius: 50%;
     width: 250px;
     height:250px;
     margin-top: +100px; 
     margin-left: +430px; 
     float: center;
    }
    .grow:hover{
    -webkit-transform: scale(1.3);
    -ms-transform: scale(1.3);
    transform: scale(1.3);
    }

    #title{
    	font-family: 'Patrick Hand SC', cursive; 
    	font-size: 100px;
    	text-align: center;
    }

    #content{
        font-family: 'Bitter', serif;
        font-size: 50px;
        text-align: center;
    }
</style>
<body style="background-color: #b2ebf2"> 
	<img class= "responsive-img img-circle grow" src="//c1.staticflickr.com/4/3836/14499517289_ab6723c4f1_b.jpg">
    <div class="row">
      <div class="col s12">
          <h2 id = "title">{{ name }}</h2>
      </div>
      <div class="col s6 blue accent-4">
            <h2 id = "title">Friends</h2>
            <p id = "content">{{ friends }} friend</p>
      </div>
      <div class="col s6 blue accent-4">
            <h2 id = "title">Latest Status</h2>
            <p id = "content">{{ latestPost }}</p>
      </div>
      <div class="col s6 red accent-4">
            <h2 id = "title">Numb of Feeds</h2>
            <p id = "content">{{ feeds }} feeds</p>
      </div>
    </div>
          
</body>
{% endblock %}

stats/templates/stats/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/stats.css' %}" /> 
</head>
<title>
    Tugas Kelompok 1
</title>
<body style="background-color: #bbdefb" class=""> 
    <header>
        {% include "profile_page/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <br>
    <footer>
      {% include "profile_page/partials/footer.html" %}
    </footer>
   
</body>
</html>

status/templates/status/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
</head>
<body style="background-color:#bbdefb">
	<header>
		{% include "profile_page/partials/header.html" %}
	</header>

	<content>
        {% block content %}
            <!-- content goes here -->
        {% endblock %}
    </content>

	<footer>
		{% block footer %}
      	{% include "profile_page/partials/footer.html" %}
     	{% endblock %}
	</footer>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}

status/templates/table.html
{% extends "lab_4/layout/base.html" %}

    {% block title %} Kumpulan Pesan {% endblock %}

    {% block content %}
    <!--  Populate semua isi pesan dari model -->
    <table class="table">
        <thead>
            <th>Pesan</th>
            <th>Dibuat Pada</th>
        </thead>
        <tbody>
        
            {% for i in message %}
            {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
            <tr class="warning"> {% else %} <tr class="success">
                {% endif %}
                <td> {{i.message}} </td>
                <td> {{i.created_date}} </td>
            </tr>             
            {% endfor %}
        </tbody>
    </table>

    {% endblock %}

status/templates/update.html
{% extends "status/layout/base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<hr/>
<style type="text/css">
    .todo-form-textarea {
        width: 100%;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <section name="input-list" id="input-list">
                <div class="container">
                    <form id="form" method="POST" action="{% url 'status:status' %}">
                        <h2>Update Status</h2>
                        <br>
                        {% csrf_token %}
                        {{ todo_form }}

                        <input id="submit" type="submit" class="btn btn-lg btn-info" value="Submit">
                        
                    </form>
                    <br>
                    
                </div>
            </section>
        </div>
        <div class="col-sm-6">
            <section name="my-list" id="my-list" style="padding-bottom: 20px">


            {% if todo %}
                {% for data in todo %}
                    
                    <div class="container">
                        <div class="row">
                        <div class="col-sm-8 col-sm-offset-2">  
                            <div class= "media" style="padding: 40px">
                                <div class= "media-left">
                                    <img src="http://image.ibb.co/dL1wDk/20170923_102934_231.jpg" class="media-object
                                    img-circle" style= "width:75px">
                                </div>
                                <div class="media-body" style="padding-left:10px">

                                    <h4 class="media-heading"><strong>{{author}}</strong> <small><i> Posted on
                                    {{data.created_date}}</i></small></h4>
                                    <p>{{data.description}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                    
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Todo.
            </div>
            {% endif %}
        <!--</div> -->
    
</section>
        </div>
    </div>
</div>



{% endblock %}